-- ===============================
-- Tabela: tb_convenio
-- ===============================
CREATE TABLE tb_convenio_teste_naty (
    id_convenio        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente        INT NOT NULL,
    dt_contratacao     DATE NOT NULL,
    vl_mensalidade     FLOAT NOT NULL,
    carencia           INT,
    cobertura          DATE,
    tipo_plano         VARCHAR2(100) NOT NULL,
    coparticipacao     VARCHAR2(1)
);

-- ===============================
-- Tabela: tb_categoria_exame
-- ===============================
CREATE TABLE tb_categoria_exame_teste_naty (
    id_categoria_exame INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao          VARCHAR2(300) NOT NULL
);

-- ===============================
-- Tabela: tb_exame
-- ===============================
CREATE TABLE tb_exame_teste_naty (
    id_exame               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                   VARCHAR2(100) NOT NULL,
    preco                  FLOAT NOT NULL,
    tempo_media_realizacao FLOAT,
    autorizacao            CHAR(1) NOT NULL,
    id_categoria_exame     INT NOT NULL,
    CONSTRAINT fk_exame_categoria
        FOREIGN KEY (id_categoria_exame)
        REFERENCES tb_categoria_exame_teste_naty (id_categoria_exame)
);

-- ===============================
-- Tabela: tb_paciente
-- ===============================
CREATE TABLE tb_paciente_teste_naty (
    id_paciente    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR2(100) NOT NULL,
    cpf            VARCHAR2(11) NOT NULL UNIQUE,
    dt_nascimento  DATE NOT NULL,
    sexo           VARCHAR2(1),
    telefone       VARCHAR2(50),
    id_convenio    INT,
    CONSTRAINT fk_paciente_convenio
        FOREIGN KEY (id_convenio)
        REFERENCES tb_convenio_teste_naty (id_convenio)
);

-- ===============================
-- Tabela: tb_medico
-- ===============================
CREATE TABLE tb_medico_teste_naty (
    id_medico  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(100) NOT NULL,
    crm        VARCHAR2(10) NOT NULL UNIQUE,
    status     VARCHAR2(1) DEFAULT 'A' CHECK (status IN ('A', 'I'))
);

-- ===============================
-- Tabela: tb_solicitacao
-- ===============================
CREATE TABLE tb_solicitacao_teste_naty (
    id_solicitacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente    INT NOT NULL,
    id_medico      INT NOT NULL,
    dt_solicitacao DATE DEFAULT SYSDATE,
    CONSTRAINT fk_solicitacao_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES tb_paciente_teste_naty (id_paciente),
    CONSTRAINT fk_solicitacao_medico
        FOREIGN KEY (id_medico)
        REFERENCES tb_medico_teste_naty (id_medico)
);

-- ===============================
-- Tabela: tb_itens_solicitacao
-- (Relacionamento N:N entre solicitacao e exame)
-- ===============================
CREATE TABLE tb_itens_solicitacao_teste_naty (
    id_solicitacao INT NOT NULL,
    id_exame       INT NOT NULL,
    PRIMARY KEY (id_solicitacao, id_exame),
    CONSTRAINT fk_itens_solicitacao_solicitacao
        FOREIGN KEY (id_solicitacao)
        REFERENCES tb_solicitacao_teste_naty (id_solicitacao),
    CONSTRAINT fk_itens_solicitacao_exame
        FOREIGN KEY (id_exame)
        REFERENCES tb_exame_teste_naty (id_exame)
);

-- ===============================
-- Tabela: tb_autorizacao
-- ===============================
CREATE TABLE tb_autorizacao_teste_naty (
    id_autorizacao  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_autorizacao  DATE NOT NULL,
    num_protocolo   INT NOT NULL,
    status          VARCHAR2(1) CHECK (status IN ('A','N','P')) NOT NULL,
    motivo_negado   VARCHAR2(300),
    id_solicitacao  INT NOT NULL,
    CONSTRAINT fk_autorizacao_solicitacao
        FOREIGN KEY (id_solicitacao)
        REFERENCES tb_solicitacao_teste_naty (id_solicitacao)
);

-- ===============================
-- Tabela: tb_agendamento
-- ===============================
CREATE TABLE tb_agendamento_teste_naty (
    id_agendamento  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_realizacao   DATE NOT NULL,
    status          VARCHAR2(50) NOT NULL,
    id_paciente     INT NOT NULL,
    id_exame        INT NOT NULL,
    CONSTRAINT fk_agendamento_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES tb_paciente_teste_naty (id_paciente),
    CONSTRAINT fk_agendamento_exame
        FOREIGN KEY (id_exame)
        REFERENCES tb_exame_teste_naty (id_exame)
);

-- ===============================
-- Tabela: tb_resultado_exame
-- ===============================
CREATE TABLE tb_resultado_exame_teste_naty (
    id_resultado        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laudo               VARCHAR2(300),
    dt_liberacao_resultado DATE,
    senha_acesso        VARCHAR2(10) NOT NULL,
    id_autorizacao      INT,
    CONSTRAINT fk_resultado_autorizacao
        FOREIGN KEY (id_autorizacao)
        REFERENCES tb_autorizacao_teste_naty (id_autorizacao)
);

-- ===============================
-- Tabela: tb_registro_financeiro
-- ===============================
CREATE TABLE tb_registro_financeiro_teste_naty (
    id_registro_fin     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente         INT NOT NULL,
    id_exame            INT NOT NULL,
    vl_exame            FLOAT NOT NULL,
    vl_pago_paciente    FLOAT,
    CONSTRAINT fk_fin_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES tb_paciente_teste_naty (id_paciente),
    CONSTRAINT fk_fin_exame
        FOREIGN KEY (id_exame)
        REFERENCES tb_exame_teste_naty (id_exame)
);

-- ===============================
-- Tabela: au_historico_exame
-- ===============================
CREATE TABLE au_historico_exame_teste_naty (
    id_status_ex_pa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente     INT NOT NULL,
    id_exame        INT NOT NULL,
    dt_status       DATE NOT NULL,
    CONSTRAINT fk_hist_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES tb_paciente_teste_naty (id_paciente),
    CONSTRAINT fk_hist_exame
        FOREIGN KEY (id_exame)
        REFERENCES tb_exame_teste_naty (id_exame)
);
